# For config details see https://alacritty.org/config-alacritty.html
# General
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
decorations_theme_variant = "None"
opacity = 0.9 # 0.85
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 166
lines = 38

[window.position]
x = 10
y = 10

[window.padding]
x = 15
y = 13

[scrolling]
history = 10000
multiplier = 3

[font]
builtin_box_drawing = true
size = 13

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

[colors.primary]
background = "#11111B"

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#70c0b1"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#eaeaea"
yellow = "#e7c547"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#864343"
white = "#828482"
yellow = "#9e824c"

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
blink_interval = 400
blink_timeout = 3
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Beam"

[cursor.style]
blinking = "Always"
shape = "Block"

[mouse]
hide_when_typing = false

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize" 
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

