import = [
    "~/dotfiles/conflicts/alacritty.toml",
]

[window.dimensions]
columns = 166
lines = 38

[window.position]
x = 10
y = 10

[window.padding]
x = 15
y = 13

[font]
size = 13

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"
